[[credentials]]
alias = "default"
comment = ""
type = "prompt"

[[scope]]
alias = "default"
comment = ""
includes = "default.list"
excludes = ""
ignores = []

[[target]]
alias = "default"
comment = ""
scope = "default"
credentials = "default"
location = "/media/${USER}/usbstick"
