# restix without GUI
[project]
name = "restix_core"
dynamic = ["version"]
authors = [
    {name="Frank Sommer", email="Frank.Sommer@sherpa-software.de"}
]
maintainers = [
    {name="Frank Sommer", email="Frank.Sommer@sherpa-software.de"}
]
description = "Backup and restore system based on restic"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "tomli",
    "tomli_w"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Topic :: System :: Archiving",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.scripts]
restix = "restix.cli.restix_cli:cli_main"

[project.urls]
Homepage = "https://github.com/frsommer64/restix"
Issues = "https://github.com/frsommer64/restixissues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
    "/.git",
    "/.pytest_cache",
    "/.idea",
    "/.venv",
    "/src/restix/gui"
]

[tool.hatch.build.targets.wheel]
packages = ["src/restix"]
exclude = ["/src/restix/gui"]

[tool.hatch.build.targets.wheel.force-include]
"templates" = "restix/templates"

[tool.hatch.version]
path = "src/restix/core/__init__.py"
