[[credentials]]
alias = "default"
comment = ""
type = "file"
value = "pw.txt"

[[scope]]
alias = "default"
comment = ""
includes = "default.list"
excludes = ""
ignores = []

[[target]]
alias = "USB-stick"
comment = ""
location = "/media/${USER}/BACKUPUSB/restix"
scope = "default"
credentials = "default"
